In [1]:
# import tensorflow libraries
import tensorflow as tf

In [2]:
#version check
print(tf.__version__)

2.12.0


In [3]:
# create a tensor with tf.constant()

scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#check the number of dimension of a tensor (ndim for number of dimension)

scalar.ndim

0

In [5]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# check the dimension of our vector
vector.ndim

1

In [7]:
#create a matrix (has more than 1 dimension)
matrix=tf.constant([[1,3],
                    [3,4]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [3, 4]], dtype=int32)>

In [8]:
#check the dimension of our matrix
matrix.ndim

2

In [9]:
#create another matrix with different data types

another_matrix=tf.constant([[1.0 , 2],
                            [3. , 4.],
                            [5. , 6. ]] , dtype=tf.float16)

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [10]:
#check dimension of another_matrix

another_matrix.ndim


2

In [11]:
# Let's create a tensor


tensor=tf.constant([[[1,2,3,],
                     [2,3,4]],
                    [[5,6,7],
                     [8,9,10]]])

tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]], dtype=int32)>

In [12]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number.
* Vector: a number with direction(e.g., wind speed and direction)
* Matrix: a 2-dimensional array of numbers.
* Tensor: an n-dimensional array of numbers.

### Creating tensors with `tf.variable`

In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
# create the same tensor with tf.variable as above

changeable_tensor=tf.Variable([10,10])
unchangeable_tensor=tf.constant([10,10])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>)

In [15]:
#let's try to change one of the elements in our changeable tensor

changeable_tensor[0].assign(15)

changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15, 10], dtype=int32)>

In [16]:
#let's try to change one of the elements in our unchangeable tensor

unchangeable_tensor[0].assign(15)

unchangeable_tensor

AttributeError: ignored

That means `tf.constant` are not supported assining a new value,but `tf.variable` are supported

### Creating Random Tensors

In random tensor are contain any arbitrary values

In [17]:
# create tensor

random_1= tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))

random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
random_2= tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [19]:
random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### create tensor with all one's or zero's

In [20]:
# create a 3*3 dimension matrix with all one's

matrix_ones=tf.ones(shape=(3,3))

matrix_ones

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [24]:
#create a 3*3 dimension matrix with all zeros

matrix_zeros=tf.zeros([3,3] , dtype=tf.int32) # if you want to specific data type
matrix_zeros

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [39]:
# check matrix shape and reshape this matrix
# must be careful number of element are equal in original matrix and reshape matrix
# for example original matrix (2*2*4)=>16 ,, so reshape matrix must be, equal number of elements when multiplied dimension( 1*16 , 2*8, 4*4, 4*2*2, etc)

matrix_shape=tf.constant([[[1,2,3,4],
                       [5,6,7,8]],

                       [[9,10,11,12],
                        [15,16,17,27]]
                       ])
matrix_shape

<tf.Tensor: shape=(2, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [15, 16, 17, 27]]], dtype=int32)>

In [40]:
matrix_reshape=tf.reshape(matrix_shape , shape=(4,2,2))

matrix_reshape

<tf.Tensor: shape=(4, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[15, 16],
        [17, 27]]], dtype=int32)>

In [42]:
# transpose any matrix

matrix_trans=tf.constant([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])
matrix_trans

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [44]:
transpose_matrix=tf.transpose(matrix_trans)
transpose_matrix

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=int32)>